### ISSUE TITLE
Fix recognize results

### ISSUE THREAD

**Issue by ivanpobeguts** [ivanpobeguts/celebrities_recognizer#2]
## Expected Behavior
Скрипт должен выдавать правильный label для тестовых данных.

## Actual Behavior
На данный момент скрипт парсит папки с фотографиями знаменитостей, определяет их лица и кладёт в папку faces. Каждому лицу сопоставляется label, связанный с конкретным актёром. Далее лица и labels передаются нейронной сети для тренировки.
Проблема состоит в том, что если передать обученной нейронной сети тестовые изображения с актёрами, сеть распознаёт их неправильно. Если взять фото из обучающей выборки, то распознавание правильное.
Лица определяются корректно, предположительно проблема в работе самой нейронной сети.

## Steps to Reproduce the Problem

  1. Запустить скрипт recognize.py
  1. Посмотреть на вывод имени знаменитости в консоли

## Specifications

  - Version: python 3.6
  - Platform: Linux, MACOS
  - Subsystem:

**Comment by denis-trofimov** [comment]
@ivanpobeguts 
# Советую описать детали, if help is **really** wanted.
 Повторю что написал в телеграм.
По git штукам искал для вас по словам "bug report template github" и нашел. 
 Предлагаю положить как написано в статье https://blog.github.com/2016-02-17-issue-and-pull-request-templates/ файлы отсюда https://github.com/stevemao/github-issue-templates/tree/master/simple себе в репо. You can put CONTRIBUTING.md, ISSUE_TEMPLATE.md, and PULL_REQUEST_TEMPLATE.md files in .github/ and everything will work as expected.

**Comment by ivanpobeguts** [comment]
> @ivanpobeguts
> 
> # Советую описать детали, if help is **really** wanted.
> Повторю что написал в телеграм.
> По git штукам искал для вас по словам "bug report template github" и нашел.
> Предлагаю положить как написано в статье https://blog.github.com/2016-02-17-issue-and-pull-request-templates/ файлы отсюда https://github.com/stevemao/github-issue-templates/tree/master/simple себе в репо. You can put CONTRIBUTING.md, ISSUE_TEMPLATE.md, and PULL_REQUEST_TEMPLATE.md files in .github/ and everything will work as expected.

@denis-trofimov ,
Добавил описание

**Comment by denis-trofimov** [comment]
Да, по поведению нейросеть не обучилась. 
> Проблема состоит в том, что если передать обученной нейронной сети тестовые изображения с актёрами, сеть распознаёт их неправильно. Если взять фото из обучающей выборки, то распознавание правильное.
На какой работе или примере ты основывался? Помню мелькали линки в описании проекта, помоги мне с этим, напиши их сюда пожалуйста.

**Comment by ivanpobeguts** [comment]
Решено с помощью добавления dlib в проект
